version: "3.7"
services:
  backend:
    build: ./packages/server
    ports:
      - 3000:3000
    image: backend
  backend-db:
    image: mongo:4.4
    ports:
      - 27017-27019:27017-27019
    volumes:
      - mongodb_data_container:/data/db
  frontend:
    build: ./packages/frontend
    ports:
      - 3001:3001
    image: frontend
volumes:
  mongodb_data_container:
