version: "3.7"
services:
  backend-db:
    image: mongo:4.4
    ports:
      - 27017-27019:27017-27019

#     volumes:
#       - mongodb_data_container:/data/db
# volumes:
#   mongodb_data_container:
